"""create notifications and budget_notification_logs tables

Revision ID: 2b458323400b
Revises: c3d6155dca7a
Create Date: 2026-07-29 01:07:43.019662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b458323400b'
down_revision: Union[str, Sequence[str], None] = 'c3d6155dca7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BUDGET_SEUIL_80', 'BUDGET_SEUIL_100', 'RAPPEL_FACTURE', 'RESUME_MENSUEL', 'SYSTEME', name='notificationtype'), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('budget_notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('seuil_type', sa.Enum('BUDGET_SEUIL_80', 'BUDGET_SEUIL_100', 'RAPPEL_FACTURE', 'RESUME_MENSUEL', 'SYSTEME', name='notificationtype'), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'seuil_type', 'periode_debut', name='uq_budget_notif_period')
    )
    op.create_index(op.f('ix_budget_notification_logs_budget_id'), 'budget_notification_logs', ['budget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_notification_logs_budget_id'), table_name='budget_notification_logs')
    op.drop_table('budget_notification_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
