"""add savings goal fields to wallet

Revision ID: 49284eaca544
Revises: cc48e69d8bdd
Create Date: 2026-08-01 03:39:12.259389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49284eaca544'
down_revision: Union[str, Sequence[str], None] = 'cc48e69d8bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE wallettype ADD VALUE IF NOT EXISTS 'epargne'")
    op.add_column('wallets', sa.Column('montant_cible', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wallets', sa.Column('date_echeance', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'date_echeance')
    op.drop_column('wallets', 'montant_cible')
    # ### end Alembic commands ###
