"""create exchange_rates table

Revision ID: 7982b67ad04a
Revises: ebb0c86506c4
Create Date: 2026-07-27 17:54:12.687715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7982b67ad04a'
down_revision: Union[str, Sequence[str], None] = 'ebb0c86506c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('devise_source', sa.String(length=3), nullable=False),
    sa.Column('devise_cible', sa.String(length=3), nullable=False),
    sa.Column('taux', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['devise_cible'], ['devises.code_devise'], ),
    sa.ForeignKeyConstraint(['devise_source'], ['devises.code_devise'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('devise_source', 'devise_cible', name='uq_exchange_rate_pair')
    )
    op.create_index(op.f('ix_exchange_rates_devise_cible'), 'exchange_rates', ['devise_cible'], unique=False)
    op.create_index(op.f('ix_exchange_rates_devise_source'), 'exchange_rates', ['devise_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_devise_source'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_devise_cible'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
