"""add unique constraint on category user_id and nom

Revision ID: ebb0c86506c4
Revises: f609ba612a83
Create Date: 2026-07-26 21:54:30.472846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb0c86506c4'
down_revision: Union[str, Sequence[str], None] = 'f609ba612a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_user_nom', 'categories', ['user_id', 'nom'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_user_nom', 'categories', type_='unique')
    # ### end Alembic commands ###
