"""create categories table

Revision ID: f609ba612a83
Revises: ff6addf7f3e1
Create Date: 2026-07-26 21:15:28.226543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f609ba612a83'
down_revision: Union[str, Sequence[str], None] = 'ff6addf7f3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('icone', sa.Enum('RESTAURANT', 'TRANSPORT', 'LOGEMENT', 'SANTE', 'EDUCATION', 'LOISIRS', 'SHOPPING', 'FACTURES', 'ABONNEMENT', 'VOYAGE', 'CADEAU', 'EPARGNE', 'FAMILLE', 'ANIMAUX', 'SPORT', 'BEAUTE', 'ASSURANCE', 'IMPOTS', 'DON', 'AUTRE', name='categoryicon'), nullable=False),
    sa.Column('couleur', sa.Enum('BLEU', 'ROUGE', 'VERT', 'ORANGE', 'VIOLET', 'ROSE', 'JAUNE', 'GRIS', 'CYAN', 'INDIGO', name='categorycolor'), nullable=False),
    sa.Column('est_par_defaut', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
